name: CI

on:
  push:
    paths-ignore:
      - .gitignore
      - README.md
  pull_request:
    paths-ignore:
      - .gitignore
      - README.md
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *' # Monthly

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: microsoft/setup-msbuild@v1.1

    - name: Build Chaos Mod (GoldSrc)
      run: msbuild /m /t:Build /p:Configuration=Release GSChaos.sln
    - name: Prepare HL artifacts
      run: |
        mv Release/GSChaos.dll .\gamedir\asi_plugins\GSChaos.asi
        mv Release/GSChaos.pdb .\gamedir\asi_plugins\
        Compress-Archive -Path .\gamedir\* -Destination GSChaos_HL.zip

    - name: Build Chaos Mod (Cry of Fear)
      run: msbuild /m /t:Rebuild /p:CoFBuild=COF_BUILD /p:Configuration=Release GSChaos.sln
    - name: Prepare CoF artifacts
      run: |
        rm .\gamedir\asi_plugins\GSChaos.asi
        rm .\gamedir\asi_plugins\GSChaos.pdb
        mv Release/GSChaos.dll .\gamedir\asi_plugins\GSChaos.asi
        mv Release/GSChaos.pdb .\gamedir\asi_plugins\
        Compress-Archive -Path .\gamedir\* -Destination GSChaos_CoF.zip

    - name: Deploy
      uses: actions/upload-artifact@v3
      with:
        name: GSChaos_CoF
        path: ./gamedir/
    - name: Check for pull request
      uses: 8BitJonny/gh-get-current-pr@2.2.0
      id: pr-check
      with:
        # Verbose setting SHA when using Pull_Request event trigger to fix #16. (For push even trigger this is not necessary.)
        sha: ${{ github.event.pull_request.head.sha }} 

    - name: Fetch artifacts
      if: ${{ always() && github.ref == 'refs/heads/master' && steps.pr-check.outputs.pr_found == 'false' }}
      uses: actions/download-artifact@v3.0.1
      with:
        path: ./

    - name: Remove old release
      if: ${{ always() && github.ref == 'refs/heads/master' && steps.pr-check.outputs.pr_found == 'false' }}
      uses: dev-drprasad/delete-tag-and-release@v0.2.1
      with:
        delete_release: true
        tag_name: continuous
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Allow GitHub to process removed release for few seconds
      if: ${{ always() && github.ref == 'refs/heads/master' && steps.pr-check.outputs.pr_found == 'false' }}
      continue-on-error: true
      run: |
        sleep 20s
        dir

    - name: Upload new release
      if: ${{ always() && github.ref == 'refs/heads/master' && steps.pr-check.outputs.pr_found == 'false' }}
      uses: softprops/action-gh-release@v0.1.15
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: | 
            GSChaos_HL.zip
            GSChaos_CoF.zip

        tag_name: continuous
        draft: false
        prerelease: true
        name: GSChaos Continuous Build